apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-app-deployment
  labels:
    app: csi-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weka-csi
  template:
    metadata:
      labels:
        app: weka-csi
    spec:
      containers:
      - name: my-frontend
        image: busybox
        volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo `date` >> /data/temp.txt; sleep 10;done"]
      volumes:
        - name: my-csi-volume
          persistentVolumeClaim:
            claimName: pvc-wekafs-dir # defined in pvc-wekafs-dir.yaml
---